
GET http://localhost:3000/spots

###

POST http://localhost:3000/spots 
Content-Type: application/json

{
    "name": "Dom Bruno",
    "email": "dom.liam@scituateschoolsri.com",
    "payment": "Venmo",
    "spot": [11, 1]
}

###

GET http://scituateparking.ddns.net:3000/spots

###

POST http://scituateparking.ddns.net:3000/spots 
Content-Type: application/json

{
    "name": "Liam Jacob",
    "email": "washburn.liam@scituateschoolsri.com",
    "payment": "Venmo",
    "spot": [1, 1]
}
